Using https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/

Basic operations on vectors and matrices (lesson 0 of MTH8302)

In [269]:
using LinearAlgebra

<h3> Vectors

In [270]:
vector1 = [1, 2, 3]
vector2 = [10, 8, 2]

# Vector addition
sum = vector1 + vector2
print("sum: ", sum)

# Vector multiplication by a scalar
product = vector1 * 99
print("\nproduct: ", product)

# Vector dot product
dot_product = dot(vector1, vector2)
print("\ndot product: ", dot_product)

dot_product2 = vector1' * vector2
print("\ndot product with transpose: ", dot_product2)

sum: [11, 10, 5]
product: [99, 198, 297]
dot product: 32
dot product with transpose: 32

In [271]:
v1 = [2, 3, 4]
v2 = ones(5)

# Outer product using kron (Kronecker product) : related but inverse vector order and needs to be reshaped.
outer_product = reshape(kron(v2,v1), (length(v1), length(v2)))
show(stdout, "text/plain", outer_product)
print("\n")

# Direct outer product
outer_product2 = v1 .* v2'
show(stdout, "text/plain", outer_product2)

3×5 Matrix{Float64}:
 2.0  2.0  2.0  2.0  2.0
 3.0  3.0  3.0  3.0  3.0
 4.0  4.0  4.0  4.0  4.0
3×5 Matrix{Float64}:
 2.0  2.0  2.0  2.0  2.0
 3.0  3.0  3.0  3.0  3.0
 4.0  4.0  4.0  4.0  4.0

In [272]:
v1 = [3, 4]

# Norm function to calculate different norms of a vector.
norm1 = norm(v1, 1)
norm2 = norm(v1, 2)
norm_inf = norm(v1, Inf)

print("Manhattan norm : ", norm1)
print("\nEuclidian norm : ", norm2)
print("\nInfinity norm : ", norm_inf)

Manhattan norm : 7.0
Euclidian norm : 5.0
Infinity norm : 4.0

<h3> Matrices

In [273]:
matrix1 = ones(2,2)
matrix2 = [1 2; 3 5]
v = [3, 1]

# Matrix addition
sum = matrix1 + matrix2
show(stdout, "text/plain", sum)
print("\n")

# Matrix multiplication by a scalar
product = matrix2 * 2
show(stdout, "text/plain", product)
print("\n")

# Matrix multiplication of a vector
matrix_vector_product = matrix1 * v
show(stdout, "text/plain", matrix_vector_product)

# Product of two matrices
a = [1 2; 3 4; 5 6]
b = [7 8; 9 10]
c = a * b
show(stdout, "text/plain", c)


2×2 Matrix{Float64}:
 2.0  3.0
 4.0  6.0
2×2 Matrix{Int64}:
 2   4
 6  10
2-element Vector{Float64}:
 4.0
 4.03×2 Matrix{Int64}:
 25   28
 57   64
 89  100

In [274]:
# Identity matrix
id_matrix = ones(3, 4)
show(stdout, "text/plain", id_matrix)

# Diagonal matrix
d = [3; 6; 9]
diag_matrix = Diagonal(d)
print("\n")
show(stdout, "text/plain", diag_matrix)

3×4 Matrix{Float64}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
3×3 Diagonal{Int64, Vector{Int64}}:
 3  ⋅  ⋅
 ⋅  6  ⋅
 ⋅  ⋅  9

In [275]:
# Transpose a matrix
m = [2 4; 2 4]
print("\n")
show(stdout, "text/plain", m)
print("\n")
show(stdout, "text/plain", m')

# Check for symmetry
s = [1 2 3; 2 5 6; 3 6 0]
print("\nIs m symmetrical? ", issymmetric(m)) # not symmetrical
print("\nIs m symmetrical? ", issymmetric(s)) # symmetrical


2×2 Matrix{Int64}:
 2  4
 2  4
2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 2  2
 4  4
Is m symmetrical? false
Is m symmetrical? true

In [276]:
m = [4 3; 6 3]

# Trace of a matrix
trace = tr(m)
print("Trace: ", trace)

# Determinant of a matrix
determinant = det(m)
print("\nDeterminant: ", determinant)

# Matrix norms
print("\nFrobenius: ", norm(m, 2))# square root of sum of squares
print("\nManhattan: ", norm(m, 1)) # sum of absolute values
print("\nInfinity: ", norm(m, Inf)) # largest value (absolute)
print("\nMinus Infinity: ", norm(m, -Inf)) # smallest value (absolute)

Trace: 7
Determinant: -6.0
Frobenius: 8.366600265340756
Manhattan: 16.0
Infinity: 6.0
Minus Infinity: 3.0

In [277]:
m = [4 3; 6 3]

# Rank and linear independance
rank1 = rank(m) # NOTE: this method is not reliable for floating point values (https://discourse.julialang.org/t/how-reliable-is-rank-a/106834/5).
print("\nRank with rank function: ", rank1)

# Rank for matrices with floating point values : use singular values (https://math.stackexchange.com/questions/3967922/singular-values-and-matrix-rank).
singular_values = svdvals(m)
rank2 = count(singular_values .!= 0) # element-wise operation (here it is a comparison)
print("\nRank by counting singular values: ", rank2)

# Test floating point matrix rank.
a = rand(5, 5) ^ 26
print("\n")
show(stdout, "text/plain", a)
print("\n")

# Small floating point values create an error in rank.
rank1 = rank(a) 
print("\nRank with rank function: ", rank1)

# Recommended approach.
singular_values = svdvals(a)
rank2 = count(singular_values .!= 0)
print("\nRank by counting singular values: ", rank2)


Rank with rank function: 2
Rank by counting singular values: 2
5×5 Matrix{Float64}:
 2.37937e10  2.99582e10  2.99753e10  2.49628e10  2.57086e10
 2.90262e10  3.65463e10  3.65672e10  3.04524e10  3.13621e10
 1.35108e10  1.70112e10  1.70209e10  1.41747e10  1.45981e10
 2.60352e10  3.27805e10  3.27992e10  2.73145e10  2.81305e10
 2.1659e10   2.72704e10  2.7286e10   2.27232e10  2.34021e10

Rank with rank function: 1
Rank by counting singular values: 5

In [278]:
# Check for linear independance 
# https://lall.stanford.edu/engr207b/notes/julia_inverses_slides.pdf
# The columns of A are linearly independent if and only if R has no 0 diagonal entries. (https://discourse.julialang.org/t/how-to-find-the-linearly-independent-columns-rows-of-a-matrix/109772/3)
a = reshape(1:9, 3, 3)'
show(stdout, "text/plain", a)
print("\n")
Q, R = qr(a)
zero_entries = count(R .== 0)
print(zero_entries == 0) # True if linearly independent (no zero entries)
print("\n")

# Other option: compare with rank
min_dimension = min(size(a)[1], size(a)[2]) # 1-based indexing
print(rank(a) == min_dimension) # True if linearly independent (rank equals smallest dimension)

3×3 adjoint(reshape(::UnitRange{Int64}, 3, 3)) with eltype Int64:
 1  2  3
 4  5  6
 7  8  9
false
false

In [279]:
# Matrix inverse.
a = [2 1; 1 3]
b = [5; 7]

show(stdout, "text/plain", a)
print("\n")

a_inv = inv(a)
show(stdout, "text/plain", a_inv)
print("\n")

# Ax = b <=> x = A^-1 b
x = a_inv * b
print("solution: ", round.(x, digits=3)) # Round to avoid the numerical error.

2×2 Matrix{Int64}:
 2  1
 1  3
2×2 Matrix{Float64}:
  0.6  -0.2
 -0.2   0.4
solution: [1.6, 1.8]

In [280]:
# Orthogonality
theta = pi / 4
R = [cos(theta) -sin(theta); sin(theta) cos(theta)] # Rotation matrix
show(stdout, "text/plain", R)
print("\n")

# Check if R is orthogonal
dot_product = R' * R
print("Is the matrix orthogonal? ", dot_product == I) # Compare to (lazy) identity matrix

# Check for preserved norm
v = [1; 0]
transformed_v = R * v

norm_v = norm(v, 2)
norm_transformed_v = norm(transformed_v, 2)
print("\nIs the Euclidean norm preserved? ", norm_v == norm_transformed_v)

2×2 Matrix{Float64}:
 0.707107  -0.707107
 0.707107   0.707107
Is the matrix orthogonal? true
Is the Euclidean norm preserved? true

In [281]:
# Eigenvalues and eigenvectors
A = [3 1; 1 3]
(evals, evecs) = eigen(A)
print("Eigenvalues: ", evals) # eigenvalues are returned in no set order.
print("\nEigenvectors:\n")
show(stdout, "text/plain", evecs) # eigenvectors are returned as columns of a matrix.

# Validate A * v = lambda * v for each eigenvector
for (i, v) in enumerate(eachcol(evecs)) # Get index with enumerate function, eachcol gets every column of a matrix.
    lambda = evals[i]
    Av = A * v
    lambda_v = lambda * v
    print("\nIs A * v = lambda * v? ", Av == lambda_v)
end

Eigenvalues: [2.0, 4.0]
Eigenvectors:
2×2 Matrix{Float64}:
 -0.707107  0.707107
  0.707107  0.707107
Is A * v = lambda * v? true
Is A * v = lambda * v? true

In [282]:
# Eigendecomposition of a matrix: A = P * Lambda * P^-1
A = [4.0 1.0; 1.0 4.0]
(evals, evecs) = eigen(A)
print("Eigenvalues: ", evals) # eigenvalues are returned in no set order.
print("\nEigenvectors:\n")
show(stdout, "text/plain", evecs) # eigenvectors are returned as columns of a matrix.

Lambda = diagm(evals) # construct a diagonal matrix with evals as diagonal values
P = evecs
P_inv = inv(P)
A_reconstructed = P * Lambda * P_inv

print("\nReconstructed from inverse: \n")
show(stdout, "text/plain", A_reconstructed) 
print("\nIs matrix A reconstructed from inverse? ", isapprox(A, A_reconstructed))

# A is a symmetrical matrix : A = P * Lambda * P^T
print("\nIs A symmetrical? ", issymmetric(A))
A_reconstructed_from_transposed = P * Lambda * P'
print("\nReconstructed from transposed: \n")
show(stdout, "text/plain", A_reconstructed_from_transposed)
print("\nIs matrix A reconstructed from transposed? ", isapprox(A, A_reconstructed_from_transposed))


Eigenvalues: [3.0, 5.0]
Eigenvectors:
2×2 Matrix{Float64}:
 -0.707107  0.707107
  0.707107  0.707107
Reconstructed from inverse: 
2×2 Matrix{Float64}:
 4.0  1.0
 1.0  4.0
Is matrix A reconstructed from inverse? true
Is A symmetrical? true
Reconstructed from transposed: 
2×2 Matrix{Float64}:
 4.0  1.0
 1.0  4.0
Is matrix A reconstructed from transposed? true

In [283]:
# Eigendecomposition of an orthogonal matrix

# Q is an orthogonal matrix : A = P * Lambda * P^T where P is orthogonal and Lambda = is a diagonal of the lambda values equal to +/- 1.
Q = [1 0; 0 -1] # reflection across x-axis
# Check if Q is orthogonal
dot_product = Q' * Q
print("\nIs the matrix Q orthogonal? ", dot_product == I) # Compare to (lazy) identity matrix

(evals, evecs) = eigen(Q)
print("\nEigenvalues: ", evals) # eigenvalues are returned in no set order.
print("\nEigenvectors:\n")
show(stdout, "text/plain", evecs) # eigenvectors are returned as columns of a matrix.

Lambda = diagm(evals) # construct a diagonal matrix with evals as diagonal values
print("\nLambda (diagonal of lambda values equal to +/- 1):\n")
show(stdout, "text/plain", Lambda)

P = evecs
# Check if P is orthogonal
dot_product = P' * P
print("\nIs the matrix P orthogonal? ", dot_product == I) # Compare to (lazy) identity matrix

Q_reconstructed = P * Lambda * P'
print("\nIs matrix Q reconstructed from inverse? ", isapprox(Q, Q_reconstructed))


Is the matrix Q orthogonal? true
Eigenvalues: [-1.0, 1.0]
Eigenvectors:
2×2 Matrix{Float64}:
 0.0  1.0
 1.0  0.0
Lambda (diagonal of lambda values equal to +/- 1):
2×2 Matrix{Float64}:
 -1.0  0.0
  0.0  1.0
Is the matrix P orthogonal? true
Is matrix Q reconstructed from inverse? true

In [284]:
# Quadratic Matrix Form 
A = [2 1; 1 3]
x = [1; 2]

# Quadratic form
q = x' * A * x
print("Result : ", q) 
print("\nIs A semidefinite positive? ", q >= 0) # >= 0, therefore it is a positive semidefinite matrix.

# Validate positive semidefinite matrix with eigenvalues.
evals = eigvals(A)
negative_evals = count(evals .< 0)
print("\nDoes A have any negative eigenvalues? ", negative_evals != 0)

Result : 18
Is A semidefinite positive? true
Does A have any negative eigenvalues? false

In [285]:
# Useful functions
v1 = [2, 2] # column vector.
v2 = [2 2]  # row vector.
m = [1 2; 2 1]

# Size of a vector/matrix.
print("\nsize of a vector: ", size(v1))
print("\nsize of a matrix: ", size(m))

# Transpose of a vector/matrix
print("\ntranspose of a vector: ", v1')
print("\ntranspose of a matrix: ", m')

# More readable display
show(stdout, "text/plain", m)
print("\n")
show(stdout, "text/plain", v1)
print("\n")
show(stdout, "text/plain", v2)

# Compare two vectors/matrices : possible with ==, but there can be some numerical errors that return a false result.
v3 = [1 rand(1) * 10^-50]
print("\n")
show(stdout, "text/plain", v3)
v4 = [1 rand(1) * 10^-50]
print("\n")
show(stdout, "text/plain", v4)
print("\nExact comparaison result : ", v3 == v4) # v3 is not exactly equal to v4.
print("\nApproximative comparison result : ",  isapprox(v3, v4, rtol = 10^-10)) # Tolerance for comparaison is 10^-10 : smaller differences are not considered.


size of a vector: (2,)
size of a matrix: (2, 2)
transpose of a vector: [2 2]
transpose of a matrix: [1 2; 2 1]2×2 Matrix{Int64}:
 1  2
 2  1
2-element Vector{Int64}:
 2
 2
1×2 Matrix{Int64}:
 2  2
1×2 Matrix{Float64}:
 1.0  7.40438e-51
1×2 Matrix{Float64}:
 1.0  6.1474e-51
Exact comparaison result : false
Approximative comparison result : true